### ISSUE TITLE
Extra decoration of red circles to show changes in failures

### ISSUE THREAD

**Issue by arthurvd** [Deltares/tcBuildViewer#13]
**Is your feature request related to a problem? Please describe.**
The current list of red and green circles shows only the overall status of a particular configuration (failed, resp. succeeded).
It is even more insightful if we can see for a failed circle, whether anything new or different has failed since the previous run.

**Describe the solution you'd like**
Idea: decorate a red circle (maybe with a purple contour line) if the amount of failures has changed compared to the previous run, or if different tests have failed/failures occurred than in the previous run.
(by definition this will always be the case for the first red circle following a green circle. But for a consecutive sequence red circles, some of them may contain new failures, and some others not.)

**Describe alternatives you've considered**
Hovering with mouse over red circles, one by one, but I find that too time-consuming.

**Comment by robin-deltares** [comment]
I added a yellow halo to build types that have changed.

The same function will be added to the individual builds for which the build-step results are changed.

https://github.com/Deltares/tcBuildViewer/issues/4
