### ISSUE TITLE
Make the panels with red-green status reports collapsible per configuration

### ISSUE THREAD

**Issue by arthurvd** [Deltares/tcBuildViewer#14]
**Is your feature request related to a problem? Please describe.**
The current list of TC status reports can become a long list, through which you can scroll.
But when scrolling up and down, it can become confusing how far you are with your "testbench corvee".

**Describe the solution you'd like**
Each panel with results (the dashed-line surrounded div's) can maybe get a small triangle to collapse it or expand it.
Just like TeamCity's own overview pages have:
![image](https://user-images.githubusercontent.com/5485622/207015022-a69170fd-73c6-4492-abf2-ff220c0de99e.png)

**Describe alternatives you've considered**
None

**Comment by robin-deltares** [comment]
We can make a button to add a (sub)project to the exclude-list and/or just to temporarily collapse it.

I need the input of developers to refine this, to understand the desired workflow.

**Comment by robin-deltares** [comment]
Is refined; collapse state does not have to be stored.
