### ISSUE TITLE
Refactor code & render optimization

### ISSUE THREAD

**Issue by robin-deltares** [Deltares/tcBuildViewer#33]
Once the most wanted features are out, there is plenty of render-optimization and code-restructuring to be done.

**Comment by robin-deltares** [comment]
Only the last two builds are compared on 'statistics' (instead of just problemOccurrences.newFailed).

This will be fixed as part of refactoring as I need to change the structure of my code.

**Comment by arthurvd** [comment]
Maybe you can benefit from these API entities:
https://www.jetbrains.com/help/teamcity/rest/problemoccurrences.html
Specifically:
```
nextHref  | string
prevHref  | string
newFailed | integer
```

**Comment by robin-deltares** [comment]
A modest (Dhydro+Dimr+FEWS) set already makes 1300+ HTTP requests and technically the data is already fetched.

But the .next/.previous elements is a great idea to 'connect' build-siblings for comparison, without extra HTTP requests.

pseudo-code:

for-loop {
  build[i].previous=build[i+1]
  build[i].next=build[i-1]
}

**Comment by robin-deltares** [comment]
Comparison with previous build now works.

**Comment by robin-deltares** [comment]
Partially optimized rendering by making lots of semi-transparent elements opaque.

**Comment by robin-deltares** [comment]
Faster queries for testoccurence data:
/app/rest/builds/id:2132464?fields=testOccurrences(count,muted,ignored,passed,failed,newFailed)
/app/rest/testOccurrences?locator=build:(id:2132464),status:FAILURE,currentlyInvestigated:false

**Comment by robin-deltares** [comment]
All the above have now been implemented.

New optimization: Only query sub-messages when un-collapsing loglines. As (for instance) FEWS has many layers and many logs.
