### ISSUE TITLE
Add optional 'important build types' to the project selection.

### ISSUE THREAD

**Issue by adrimourits** [Deltares/tcBuildViewer#49]
Artifacts from D-Hydro builds are picked-up by the collectors.
Artifacts from the collectors are used to run testbenches.

If something is broken in this chain, the testbenches will not run and no new run-data will be available.

Suggestion (easy to implement):
Mark some projects as crucial (with parameter "tcBuildViewer_crucial=1"). If a crucial project fails it should be shown at the top.

Alternative (more time consuming):
Trace project dependencies automatically. If a dependency is broken, replace the full line by an error message

**Comment by robin-deltares** [comment]
I think I will make a mock-up of how this can be presented to the user, so you can verify if that is how you'd envision it.

**Comment by robin-deltares** [comment]
@adrimourits

1. For buildTypes (or: build configurations) I can easily extract dependencies from the API. Would you want the project to display a concatenation of underlying dependencies?
1. Can you give feedback on the following proposal?

Parameters within TeamCity:
- Free-format (one or more, space separated) user-defined classes for projects, e.g.: `tcBuildViewer_classes = "critical"`

The project selection (json) can order these optional classifications:
```
selection = {

    class_priority: [
        "critical",
        "warning",
    ],

    include_projects: [
        "MyProject1",
        "MyProject2",
    ],

    exclude_projects:[
        "ArchivedProjects",
        "ExperimentalProject",
    ],

}
```

Class styling (css/project_classes.css) illustration:

```
.project:is(.critical:has(.buildType.FAILURE)) {
    font-size: 1.2em;
    font-weight: bold;
    color: white;
    background-color: red;
}
.project:is(.warning:has(.buildType.FAILURE)) {
    font-size: 1em;
    color: black;
    background-color: orange;
}
```

**Comment by robin-deltares** [comment]
After deliberation with Jeroen and Adri, we have opted for a more practical solution.

Optional 'important build types' can be added to the project selection:

```
{
  "important_buildtypes": [
    "Dimr_DimrCollectors_1aDimrCollectorDailyLnx64",
    "Dimr_DimrCollectors_1aDimrCollectorDailyWin64"
  ],
  "include_projects": [
    "Dimr_DimrCollectors_1aDimrCollectorDailyWin64"
  ],
  "exclude_projects": []
}
```

These build types (or: "build configurations") will be shown on top of the page, before the projects.
