### ISSUE TITLE
Exact figures and percentages

### ISSUE THREAD

**Issue by adrimourits** [Deltares/tcBuildViewer#50]
[teamcity_retrieve_daily_engine_test_status_873_20221215.txt](https://github.com/Deltares/tcBuildViewer/files/10236413/teamcity_retrieve_daily_engine_test_status_873_20221215.txt)

See attached overview.

It would be nice to collect and show exact figures, so:
For each testbench:
1. Total number of testcases
2. Number of passed testcases
3. Number of failed testcases
4. Number of exceptions
5. Number of ignored testcases
6. Number of muted testcases
7. Percentage green

For each group of testbenches (for each higher folder level):
1. Total number of testcases
2. Number of passed testcases
3. Percentage green

Condition: TeamCity projects that do not run a testbench (but compile or collect) should be ignored

**Comment by robin-deltares** [comment]
The interface now shows a lot of this info per buildType (aka build configuration).
These numbers will be added up for the projects after refactoring the code.
