### ISSUE TITLE
Give an overview of assigned and unassigned failing testcases

### ISSUE THREAD

**Issue by jjnoort** [Deltares/tcBuildViewer#52]
When a test case is failing, it is helpful to see if a person is assigned for investigation and who that person is  If possible it would also be helpful to see how long this testcase is assigned to a certain person. 
Unassigned testcases are also interesting because for that, the testbench corvee-er must find a victim.

**Comment by robin-deltares** [comment]
- Query assignments after the page is loaded.
- Add a marker to the buildType if a failed test case ('step') is NOT assigned.
- Add another marker if every failed test step is assigned.
- If you hover over the marker, you'll see the steps and who (and how long) it is assigned to.
- Add threshold how old a stap can be assigned and give a warning when exceeded.
- Add filter to see only unassigned or old assignments.

The TeamCity buildType page is a fallback for further information. The notification to take a look is the issue.
