### ISSUE TITLE
Treat 'default' (main/master/trunk/...) branch the same as no branch

### ISSUE THREAD

**Issue by robin-deltares** [Deltares/tcBuildViewer#73]
TeamCity has a build:(defaultBranch) value that can be used for this.

**Comment by robin-deltares** [comment]
The default branch filter is now active, but when no branch information is available for a build type, it should show every build.

**Comment by jeroen-deltares** [comment]
By using branch:default:true this issue should be fixed as of:
[49 add optional important build types to the project selection ](https://github.com/Deltares/tcBuildViewer/commit/ef9cddba483610d90eb460a67adf38bfb2821eaa)
