### ISSUE TITLE
Handle >100 messages in build log

### ISSUE THREAD

**Issue by robin-deltares** [Deltares/tcBuildViewer#84]
Any log query is capped at 100 messages, it seems.

There should be pagination of some sort, or the user should be informed and redirected to TeamCity to view the rest of the logs.

**Comment by jeroen-deltares** [comment]
After speaking with Alja and reviewing the code:
Remove the normal messages from the log and only show warning and error.
At the bottom add a button to teamcity to view full logs.

**Comment by robin-deltares** [comment]
> After speaking with Alja and reviewing the code: Remove the normal messages from the log and only show warning and error. At the bottom add a button to teamcity to view full logs.

I agree.
